# Generated by Django 5.0.7 on 2024-07-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('nombreDeporte', models.CharField(max_length=50)),
                ('idEquipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('escudo', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/8/8d/Escudo_de_la_Federaci%C3%B3n_Ecuatoriana_de_F%C3%BAtbol_2019.jpg')),
                ('color', models.CharField(max_length=50)),
                ('puntosConseguidos', models.IntegerField()),
                ('deportistaList', models.ManyToManyField(to='Personas.deportista')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.entrenador')),
                ('reglaList', models.ManyToManyField(to='Futbol.regla')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('puntuacionEquipo1', models.IntegerField()),
                ('puntuacionEquipo2', models.IntegerField()),
                ('resultado', models.CharField(max_length=50)),
                ('eventoList', models.CharField(choices=[('SANCION', 'Sanción'), ('GOL', 'Gol'), ('CAMBIO', 'Cambio'), ('LESION', 'Lesión'), ('PENAL', 'Penal'), ('FUERA_JUEGO', 'Fuera de Juego'), ('OTRO', 'Otro')], max_length=50)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='Futbol.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInscripcion', models.DateField()),
                ('equiposInscritos', models.ManyToManyField(to='Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('maxParticipantes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('LIGA', 'Liga'), ('LIGUILLA', 'Liguilla'), ('EXHIBICION', 'Exhibicion'), ('PLAY_OFF', 'Play Off'), ('SUIZO', 'Suizo'), ('OTRO', 'Otro')], max_length=50)),
                ('campeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeon', to='Futbol.equipo')),
                ('encuentroList', models.ManyToManyField(to='Futbol.encuentro')),
                ('equipoList', models.ManyToManyField(to='Futbol.equipo')),
                ('juezList', models.ManyToManyField(to='Personas.juez')),
                ('subcampeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcampeon', to='Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicionList', models.ManyToManyField(to='Futbol.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Futbol.torneo')),
            ],
        ),
    ]
