# Generated by Django 5.0.7 on 2024-07-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Futbol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombreDeporte',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='reglaList',
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='resultado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeporte', models.CharField(max_length=50)),
                ('reglaList', models.ManyToManyField(to='Futbol.regla')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
